# Generated by Django 5.2.6 on 2025-10-04 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商家编号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商家名称")),
                ("hall", models.CharField(max_length=50, verbose_name="食堂号")),
                ("location", models.CharField(max_length=50, verbose_name="窗口号")),
                (
                    "contact_info",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系方式"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="商家描述"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="营业状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商家",
                "verbose_name_plural": "商家",
                "db_table": "merchants",
                "unique_together": {("hall", "location")},
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="菜品编号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="菜品名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="菜品描述"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("饭", "饭"),
                            ("面", "面"),
                            ("饺子", "饺子"),
                            ("其他", "其他"),
                        ],
                        max_length=10,
                        verbose_name="品类",
                    ),
                ),
                (
                    "taste",
                    models.CharField(
                        choices=[
                            ("辣", "辣"),
                            ("咸", "咸"),
                            ("淡", "淡"),
                            ("酸甜", "酸甜"),
                        ],
                        max_length=10,
                        verbose_name="口味",
                    ),
                ),
                (
                    "spice_level",
                    models.IntegerField(default=0, verbose_name="辣度等级"),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="菜品图片"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(default=0, verbose_name="库存数量"),
                ),
                (
                    "ai_tags",
                    models.JSONField(blank=True, default=dict, verbose_name="AI标签"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="canteen.merchant",
                        verbose_name="商家",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜品",
                "verbose_name_plural": "菜品",
                "db_table": "dishes",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="订单编号"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单总金额"
                    ),
                ),
                ("item_count", models.IntegerField(verbose_name="菜品总数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("confirmed", "已确认"),
                            ("preparing", "制作中"),
                            ("ready", "待取餐"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "ai_recommendation_score",
                    models.FloatField(blank=True, null=True, verbose_name="AI推荐得分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canteen.merchant",
                        verbose_name="商家",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="小计"
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canteen.dish",
                        verbose_name="菜品",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="canteen.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单项",
                "verbose_name_plural": "订单项",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_categories",
                    models.JSONField(default=list, verbose_name="偏好品类"),
                ),
                (
                    "preferred_tastes",
                    models.JSONField(default=list, verbose_name="偏好口味"),
                ),
                (
                    "price_range_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最低价格",
                    ),
                ),
                (
                    "price_range_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=999.99,
                        max_digits=10,
                        verbose_name="最高价格",
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.JSONField(default=list, verbose_name="饮食限制"),
                ),
                (
                    "ai_profile",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="AI用户画像"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好",
                "verbose_name_plural": "用户偏好",
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="FootTraffic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键"
                    ),
                ),
                ("traffic_count", models.IntegerField(verbose_name="客流量")),
                ("record_date", models.DateField(verbose_name="记录日期")),
                (
                    "time_slot",
                    models.CharField(
                        choices=[("早餐", "早餐"), ("午餐", "午餐"), ("晚餐", "晚餐")],
                        max_length=10,
                        verbose_name="时间段",
                    ),
                ),
                (
                    "ai_prediction",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="AI预测数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canteen.merchant",
                        verbose_name="商家",
                    ),
                ),
            ],
            options={
                "verbose_name": "客流量",
                "verbose_name_plural": "客流量",
                "db_table": "foot_traffic",
                "unique_together": {("merchant", "record_date", "time_slot")},
            },
        ),
    ]
